AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pe.ts lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters: 
  TableName: 
    Type: String
    Default: pets
  ImageBucketName:
    Type: String
    Default: pets.soe.dpe-au.io-images

Resources:
  PetsTable:
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName:
        Ref: TableName

  PetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName:
        Ref: ImageBucketName

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # TODO not working?
      # DefinitionBody:
      #   Fn::Transform:
      #     Name: AWS::Include
      #     Parameters:
      #       Location: ../api/api.yaml
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  CreatePetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: createPetFunction.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DB_TABLE: !Ref TableName
          IMAGE_BUCKET: !Ref ImageBucketName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PetsTable
        - S3CrudPolicy:
            BucketName: !Ref PetsS3Bucket
        - RekognitionDetectOnlyPolicy: {}
      Events:
        CreatePet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pets
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
  
  GetPetStatsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: getPetStatsFunction.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DB_TABLE: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PetsTable
      Events:
        GetPetStats:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /petStats
            Method: get
            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PetsApi:
    Description: "API Gateway endpoint URL for Prod stage for Pets function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets/"
  CreatePetFunction:
    Description: "Create Pet Lambda Function ARN"
    Value: !GetAtt CreatePetFunction.Arn
  CreatePetFunctionIamRole:
    Description: "Implicit IAM Role created for Create Pet function"
    Value: !GetAtt CreatePetFunctionRole.Arn
  GetPetStatsFunction:
    Description: "Get Pet Stats Lambda Function ARN"
    Value: !GetAtt GetPetStatsFunction.Arn
  GetPetStatsFunctionIamRole:
    Description: "Implicit IAM Role created for Get Pet Stats function"
    Value: !GetAtt GetPetStatsFunctionRole.Arn