# This workflow will deploy api folder content to S3

name: Deploy API

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  workflow_dispatch: {}

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    - run: aws s3 sync . s3://pets.soe.dpe-au.io
      env:
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
