# This workflow will run unit tests on the lambda directory
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Verify UI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'ui/**'

defaults:
  run:
    working-directory: ui

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm test